[project]
name = 'tokenizedrealestate'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.tokenizedrealestate]
path = 'contracts/tokenizedrealestate.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
